#!/bin/sh

onvifLogDir="/etc/aqueti/Log/"
usrName=$(who |awk -F' ' '{print $1}')
echo "$usrName"
sudo chown -R "$usrName":"$usrName" "/etc/aqueti"

if [ ! -d "$onvifLogDir" ]; then
	mkdir "$onvifLogDir"
	chown "$usrName":"$usrName" "$onvifLogDir"
	chmod -R 777 "$onvifLogDir"
else
	echo "Log Dir is exit.need do nothing."
fi
